--Esse script permite futura opção de troca de teclas controlada pelo usuário!

return {
	
	InputMap = {
		input0 = Enum.UserInputType.MouseButton1,
		input1 = Enum.KeyCode.LeftShift,
		input2 = Enum.KeyCode.One,
		input3 = Enum.KeyCode.Two,
		input4 = Enum.KeyCode.Three,
		input5 = Enum.KeyCode.Four,
	},
	InputToSkill = {
		input0 = 1, --m1
		input1 = 2, --dash
		input2 = 3, --skill1
		input3 = 4, --skill2
		input4 = 5, --skill3
		input5 = 6  --ult
	}
}
